baseURL = 'https://misahwan.github.io/MyBlog/'
languageCode = 'en-us'
title = 'Misa Blog'
theme = 'PaperMod'

[params]
    defaultTheme = "auto"
    ShowThemeToggle = true
    ShowReadingTime = true
    ShowShareButtons = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = true